### ISSUE TITLE
basenameAsNamespace a missing

### ISSUE THREAD

**Issue by gibson** [alienfast/i18next-loader#13]
Hello, i use `basenameAsNamespace: true` option for use files as namespace and in console its dumps as ok, but in bundle i does not have namespaces at all. Only translation keys

**Comment by rosskevin** [comment]
This is tested here:
https://github.com/alienfast/i18next-loader/blob/develop/test/basename.spec.js

Given the information provided, there is nothing I can do to help.

If you think there is a bug, please PR another scenario to the test and I will take a look.

**Comment by rosskevin** [comment]
The dumped information in the log is exactly what is in the bundle and loaded via webpack.  I have to assume since there is no follow up that this is an incorrect configuration of i18next or usage of i18next.  If you have more information I'd be happy to help but as-is this does not appear to be a bug.
