### ISSUE TITLE
nothing works as expected

### ISSUE THREAD

**Issue by jerome-diver** [alienfast/i18next-loader#18]
I'm trying what your Readme page said (option 1) to build json files with webpack builder, and then did exactly the same... but nothing is working as expected.
Please, can you try it and if it doesn't works and the project is no more maintained, i suggest to remove it from i18next official plugins to not pollute users.
Thank you to understand and for your time.

**Comment by rosskevin** [comment]
It works fine, tests pass, and the project is maintained.

**Comment by jerome-diver** [comment]
@rosskevin i'm happy that it works fine for you and it is still maintained. So you can probably help me to fix the problem ?
Because actually, as you can read, it doesn't works for me and i have no clue why.
If you want to help me, could you give me some clue about:
What i can do to find why ? 
(and please, don't close the thread there)

**Comment by rosskevin** [comment]
You can set `"debug": true` in the options and see if that gives you any insight, other than that I won't be able to help as there is simply too much variability in different environment setups.

**Comment by rosskevin** [comment]
Another tact: if debug true doesn't give you what you want, simply edit the js file in your `node_modules` directory and start putting in more `console.info()` lines to figure out your issue.  If you figure it out and think that more helpful info could be added to the debug option, just PR the additional lines.

**Comment by jerome-diver** [comment]
yes, the react-i18next is working fine client side. I have to learn a bit how to use it in SSR mode with Express.js framework.
My problem there is that i tryed to use your module for build the bundled json file with webpack. And it is precisely this who doesn't works.
For make i18next recognize json file (so to bundle json file) i'm using with webpack-4 file-load plugin and target on /\.json$/ and exclude node_modules ones, re-orient publicPath to provide content and then, create a factice constant for each in i18n.js file to let webpack read them and bundle.
Actualy, i can go without your module, but i stay confused and would like to investigate to find why exactly when i follow your Readme file nothing is happening more.
well... i will investigate on time and if i find, i will be back to inform you.
I was also thinking that if you let this thread open, some other users would be able to target something. But it seems to be very important for you to let it close (i don't understand why, but anyway... it is your way to practice).

**Comment by rosskevin** [comment]
If open source projects left every issue open where a user could not get something to work, but did not know why, issue trackers would be useless due to the high noise to signal ratio.

No evidence of a defect is apparent, tests still pass, and many others use it successfully.  Your environment, tooling, and setup are outside the purview of this project.

There is no action for this project to take on this issue, so it is closed.  This issue is still searchable and commentable, it is not locked, so if others have the same problem they are free to comment.

Given no others have reported the problem, the simplicity and stability of both this module and the i18next module, it seems likely this is a problem you have and not a problem with this project.
